### ISSUE TITLE
Only runs on 2 Batches error

### ISSUE THREAD

**Issue by edj4960** [jdayton3/Confounded#32]
Doesn't work with more than 2 Batches.

Error From Command-Line:

```
Traceback (most recent call last):
  File "autoencoder.py", line 58, in <module>
    c.targets: labels,
  File ".../session.py", line 877, in run
    run_metadata_ptr)
  File ".../session.py", line 1076, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 1) for Tensor 'discriminator/Placeholder:0', which has shape '(?, 20)'
```

Error was created by using a test file with 100 rows of data where each batch had the same data values.

**Comment by jdayton3** [comment]
Resolved by #38
